server:
  port: 8061
  servlet:
    context-path: /resources-manager

spring:
  application:
    name: resources-manager

  docker:
    compose:
      file: docker/docker-compose.yml

  liquibase:
    change-log: classpath:/db/liquibase/liquibase-master.xml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/resourcesmanager
    username: liquibase
    password: liquibase
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      linger-ms: 1
      buffer-memory: 33554432
      compression-type: lz4
      batch-size: 16384
      max-request-size: 1048576
      request-timeout-ms: 30000
      delivery-timeout-ms: 120000

    consumer:
      group-id: resources-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 1000
      session-timeout-ms: 30000
      heartbeat-interval-ms: 3000
      max-poll-records: 500
      fetch-min-size: 1
      fetch-max-wait: 500

logging:
  level:
    liquibase: INFO
    liquibase.executor: DEBUG
    liquibase.changelog: DEBUG
    liquibase.database: DEBUG
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO
    com.martinluik.resourcesmanager: INFO
